[pytest]
testpaths = tests
addopts =
    -v
    --tb=short
    --alluredir=reports/allure-results
    --html=reports/html/report.html
    --self-contained-html

markers =
    smoke:      Core happy-path tests
    regression: Full regression suite
    api:        API-only tests
    e2e:        End-to-end hybrid tests
    negative:   Negative / error-path tests

; log_cli = false
; log_cli_level = INFO
; log_format = %(asctime)s | %(levelname)-8s | %(name)s | %(message)s
; log_date_format = %H:%M:%S
