[pytest]
testpaths = tests
addopts =
    -v
    --reruns 1
    --reruns-delay 2
    --tb=short
    --alluredir=reports/allure-results
    --html=reports/html/report.html
    --self-contained-html

markers =
    smoke:      Core happy-path tests
    regression: Full regression suite
    api:        API-only tests
    e2e:        End-to-end hybrid tests
    negative:   Negative / error-path tests


