from core.mcp.llm_client import MCPClient


class LLMFailureAnalyzer:

    def __init__(self):
        self.client = MCPClient()

    def analyze(self, test_name, error_message, current_url=None):
        llm_analysis = self.client.ask_json(
            system_prompt=(
                "You are a senior QA automation assistant. Analyze Selenium, "
                "pytest, API, Grid, and Jenkins failures. Return only JSON."
            ),
            user_prompt=(
                f"Test name: {test_name}\n"
                f"Current URL: {current_url}\n"
                f"Error message:\n{error_message}\n\n"
                "Return JSON with keys: test, summary, possible_causes, "
                "recommendation, rerun_recommended."
            ),
        )

        if llm_analysis:
            llm_analysis.setdefault("test", test_name)
            llm_analysis.setdefault("error", str(error_message))
            llm_analysis.setdefault("current_url", current_url)
            return llm_analysis

        return {
            "test": test_name,
            "summary": "Failure analysis generated by MCP layer",
            "possible_causes": [
                "Locator may have changed",
                "Page may not have loaded fully",
                "Test data may be invalid",
                "Grid/browser session may be unstable"
            ],
            "error": str(error_message),
            "current_url": current_url,
            "recommendation": "Check locator stability, screenshot, DOM readiness, and retry logs."
        }
